### ISSUE TITLE
Option to disable XHR Proxy

### ISSUE THREAD

**Issue by ChiroxV** [Microsoft/vscode-cordova#168]
I didn't find an option to turn the xhr proxy off. With the xhr proxy I get the following issue:
_Failed to load resource: net::ERR_EMPTY_RESPONSE (http://localhost:8000/xhr_proxy?rurl=https://companyservice/)_

After commenting out the content of the init()-function in xhr-proxy.js it worked perfectly.

corodva-simulate documented a property named corsproxy to turn it off. But I can't set it in the debugging options (launch.json) or simulator options (when running without debugger). Adding this option to a future release would be great.

**Comment by MSLaguana** [comment]
I'd like to try and understand why the XHR proxy doesn't work for you, are you able to share a sample of how you are trying to use it?

I will also expose the ability to disable the proxy, that's quite reasonable.

**Comment by ChiroxV** [comment]
I will try to reproduce it in a smaller environment to create a sample. If possible...

**Comment by MSLaguana** [comment]
Were you able to get a smaller example of when the XHR proxy failed you @ChiroxV ?

**Comment by ChiroxV** [comment]
Sorry for my late response. No, I can only reproduce it in the company environment. I assume it's a proxy or firewall setting. @MSLaguana

**Comment by panarasi** [comment]
@ChiroxV Thanks for reporting the issue. We tried reproducing the issue but did not have any luck. We are also not hearing this issue from other customers. 
Since we do not have a repro, lets close this issue. If you think that this is a problem, can you please re-open it ?

**Comment by sijad** [comment]
I have similar problem

```
$ curl 'http://localhost:8000/xhr_proxy?rurl=http%3A//x.x.x.x/path/login' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36' -H 'Content-Type: text/plain' --data 'grant_type=password&username=usr&password=pwd' -v
*   Trying ::1...
* Connected to localhost (::1) port 8000 (#0)
> POST /xhr_proxy?rurl=http%3A//x.x.x.x/path/login HTTP/1.1
> Host: localhost:8000
> Accept: */*
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
> Content-Type: text/plain
> Content-Length: 50
> 
* upload completely sent off: 50 out of 50 bytes
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

note `GET` request works, `POST` requests with empty body also works.

**Comment by andreujuanc** [comment]
I have the same issue:

 - Created a blank project
 - Added browser platform
 - Open "code ." and added this extension.
 - Added Azure Mobile Js Client script.

Then on device ready:
```
var clientRef = new WindowsAzure.MobileServiceClient('mynodejsendpoint.azurewebsites.net');
            var todoTable = clientRef.getTable('CheckHistorico');
            todoTable.read()
                .then(function(data){
                        console.log('data', data);      
                },
                function(error){
                    console.log('le error', error);
                });
```

If I run it using CLI it works fine.

**Comment by MSLaguana** [comment]
This looks like an error in cordova-simulate, which I believe should be fixed by https://github.com/Microsoft/cordova-simulate/pull/174

**Comment by lhrolim** [comment]
as a quick remark, I think you forgot to append the "corsproxy:false"  into yours readme.md documentation.

I had to dig into the PR (https://github.com/Microsoft/vscode-cordova/pull/169) to check it out.
