### ISSUE TITLE
Unable to debug Ionic 2 app

### ISSUE THREAD

**Issue by clementino36** [Microsoft/vscode-cordova#223]
I had the same issue as #215 and fixed it by modifying `cordovaDebugAdapter.js` as suggested by MSLaguana.
Then i had the same issue as #201  and fixed it by modifying `consoleHelper.js` with `outputText = m.text;`
Right now my debug console does not show any error message anymore, but I still cannot use the debugger's features: nothing is shown in the `Variables`, `Watch` and `Call stack` panels and the `Step Over`, `Step Into` and `Step Out` buttons are greyed out. 
Also, when I am launching the `Simulate Android in browser` mode, the debug console stays on `Attaching to app` and the browser keeps loading forever.

Thanks!

**Comment by clementino36** [comment]
Anyone ?

**Comment by KinsonDigital** [comment]
I personally have not encountered this issue.  But of course I have not made a custom event and tried to hit a breakpoint in it.  If I do come across this then I will be sure to say something in this thread.

**Comment by clementino36** [comment]
I have also tryed to run the debugger in `Serve to the browser (ionic serve)` mode and I am getting this:

> Launching for serve (This may take a while)...
> Starting Ionic dev server (live reload: true)
> The Ionic live reload server exited unexpectedly
> Error in the Ionic live reload server:
> Error: Cannot read property 'hasOwnProperty' of undefined

**Comment by KinsonDigital** [comment]
Have you tried to do this without live reload?  Setting live reload to false?

**Comment by clementino36** [comment]
Yes, still the same error.
I have a feeling it has something to do with the debugger's installation or something since I can't run it in any mode. Though I simply installed Cordova Tools via VSCode's Marketplace the easiest possible way...

**Comment by tangorri** [comment]
Loose many times still can't debug in anyway :'(

**Comment by MSLaguana** [comment]
What happens if you try to manually run `ionic serve --nobrowser` in your project folder? That's the command that we are running which is resulting in an error when you try to serve to browser.

**Comment by tangorri** [comment]
I got it working using ionic serve -b, I can even inspect the app from chrome once 'ionic emulate -l'

**Comment by MSLaguana** [comment]
What version of ionic are you using?

**Comment by tangorri** [comment]
ionic2-rc4

**Comment by tangorri** [comment]
sorry my issue is not the same, on don't get the loading forever

**Comment by clementino36** [comment]
Hi,

`ionic serve --nobrowser` runs fine

> ionic-app-scripts serve "--nobrowser"
> 
> keywords if/then/else require v5 option
> [09:24:53]  ionic-app-scripts 0.0.47
> [09:24:53]  watch started ...
> [09:24:53]  build dev started ...
> [09:24:53]  clean started ...
> [09:24:53]  clean finished in 17 ms
> [09:24:53]  copy started ...
> [09:24:53]  transpile started ...
> [09:24:57]  transpile finished in 3.87 s
> [09:24:57]  webpack started ...
> [09:24:57]  copy finished in 4.03 s
> [09:25:04]  webpack finished in 7.58 s
> [09:25:04]  sass started ...
> [09:25:06]  sass finished in 1.63 s
> [09:25:06]  build dev finished in 13.13 s
> [09:25:06]  watch ready in 13.24 s
> [09:25:06]  dev server running: http://localhost:8100/

Note that I can launch my app with `ionic serve` or run it on a device/emulator without problems, I just can't launch it via the debugger.

**Comment by MSLaguana** [comment]
I believe that this should be fixed by https://github.com/Microsoft/vscode-cordova/pull/230 when we publish a new version.

**Comment by MSLaguana** [comment]
I have just published a new version, so this should be fixed.

**Comment by clementino36** [comment]
I am still having a lot of trouble making this work.

`Serve to the browser (ionic serve)` is still giving me the same error.
`Run Android on device` works only when my app is already running! When it's not, I am getting `Unable to find localabstract name of cordova app` again.
But let's admit it is working and break it down here because I think I am missing some essential stuff.
I have 2 breakpoints in the constructor of page on these 2 lines:

> console.log("1");
> console.log("2");

Whenever i launch the debug, the breakpoints go from red to a grey circle (unverified breakpoints) and then disappear and move down to another function of my code. Plus, the logs aren't shown in the debug console.
What I would expect it to do is stop at the first breakpoint, then let me decide to go to the next one, inspect variables etc... Whatever actions a debugger would be there for.
Moreover, the left panels of the debugger are still empty and the upper buttons still greyed out (refer to my original post).
Same behaviour with `Attach to running android on device`.
What am I missing here ??

If needed:
Device - Samsung Galaxy S4
OS - Windows 10
Latest versions of ionic, cordova, node js, cordova tools.

**Comment by tony-krnl** [comment]
Same here - Galaxy S3 & S5 w/ Win10.

**Comment by jmesa-sistel** [comment]
I think the best way to debug an ionic2 app in an android device is to use:
`ionic run android -l`
then
`Attach to running android on device`

And add 
```
"config": {
    "ionic_bundler": "webpack",
    "ionic_source_map": "source-map"
  },
```
in `package.json` to be able to debug properly.

**Comment by MSLaguana** [comment]
@clementino36 the problem with breakpoints moving around sounds like source maps aren't configured correctly. When you set a breakpoint on a line, say line 28 in `foo.ts`, we look up a source map to find what line and column that corresponds to, maybe like 2875 column 30 after compilation and bundling. We then ask the browser to set a breakpoint around there, but sometimes you can't set it exactly at that point so it moves a little (if you set a breakpoint in the middle of an expression for example). Then, to show where the breakpoint really got set, we convert back from where it was set, perhaps 2874 column 15, to the source file corresponding to that, which might be a different line.

This is what makes sourcemaps jump around at runtime, once we have the source mapping information available. If you are seeing breakpoints jump to unrelated functions, it could be a sign that your source maps aren't configured correctly.

Also, if you aren't seeing your console statements printed, it could be because they happen prior to when we attach. You could try `document.location.reload()` in the debugger to trigger the app to reload while you are attached, and then you should see any console log statements which are executed.

**Comment by clementino36** [comment]
@MSLaguana thank you for your explanations.
@jmesa-sistel those two lines did the trick! 
`Attaching to running android on device` is the only debugging mode that works but it will do for now (happy I can finally debug).

Why doesn't `package.json` updates itself when installing Cordova Tools though ? I can't believe I could not find anything on this eventhough it was that simple.
Thanks again.

**Comment by vladimir-kotikov** [comment]
I guess that the problem w/ breakpoints has been resolved, so I'm going to close this. @clementino36, If you still having any issues w/ this, feel free to reopen.

Also, we're going to verify and add instructions about adding ionic configuration to package manifest to the README (https://github.com/Microsoft/vscode-cordova/issues/228#issuecomment-285317888)
