### ISSUE TITLE
Yesterday, suddenly can not debug!

### ISSUE THREAD

**Issue by mingdong88** [Microsoft/vscode-cordova#460]
## Actual Behavior
1.I have a project where I was debugging in the browser and it worked great. Yesterday, suddenly can not debug!
2.Pressing the debug button will not pop up the chrome window

## Expected Behavior
1.
2.

## Software versions
- Cordova VS Code extension version: 1.6.0
- VSCode version: 1.29.1
- OS platform and version: windows 10
- NodeJS version: 10.14.1
- Cordova version: 8.1.2
- Cordova-Android/iOS/Windows version: Android 7.1.4

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
PASTE OUTPUT HERE
```
- Output of the Cordova output channel (View -> Toggle Output -> Select Cordova in ListBox):
```
PASTE OUTPUT HERE
```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
PASTE OUTPUT HERE
```

**Comment by SounD120** [comment]
@mingdong88 do you have any error messages? The lack of outputs it is unfortunately a VS Code 1.29 bug, and it were fixed already in [VS Code Insiders version](https://code.visualstudio.com/insiders/). It would be very helpful for us if you try to run your debug scenario via VS Code Insiders and fill the outputs. It would help to understand the situation from our side.

**Comment by krombipils** [comment]
Today I noticed the same bug. I don't know what was changed on my system, debug was working fine yesterday and suddenly it was broken.
This is the message I see in the log after I installed vs code insider version:

[2018-12-04 18:39:07.351] [renderer1] [error] Cannot read property '2' of null: TypeError: Cannot read property '2' of null
	at C:\Users\andre\.vscode-insiders\extensions\vsmobile.cordova-tools-1.6.0\node_modules\cordova-serve\src\browser.js:222:57
	at ChildProcess.exithandler (child_process.js:279:7)
	at emitTwo (events.js:126:13)
	at ChildProcess.emit (events.js:214:7)
	at maybeClose (internal/child_process.js:925:16)
	at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:209:5)

After I manually added the fix from [https://github.com/apache/cordova-serve/pull/11/commits](url), everything is fine again.

**Comment by mingdong88** [comment]
@SounD120 
Tested in ad, the problem still exists and there is no output. It should be because it has not entered the debugging stage.

Testing in another Windows 10 system, the problem still exists

The previous version (1.5.1) had no problem. Chrome can start debugging normally

No problem in Mac. Chrome can start debugging normally



Chrome will not start in Windows 10.

After I try to start chrome manually, I can run app by typing http://localhost:8000/simulator/index.html in the address bar, but I can't debug because there is no output display.

**Comment by krombipils** [comment]
@ mingdong88

Have you tried to apply the patch from [https://github.com/apache/cordova-serve/pull/11/commits](https://github.com/apache/cordova-serve/pull/11/commits)?
I guess you are also running a non-US version of windows and this patch fixes an issue on these versions. Just replace `var regItemPattern = /\s*\(Default\)\s+(REG_SZ)\s+([^\s].*)\s*/;` with `var regItemPattern = /\s*\(.*\)\s+(REG_SZ)\s+([^\s].*)\s*/;` in your browser.js.
For me it is located under ~UserFolder\.vscode\extensions\vsmobile.cordova-tools-1.6.0\node_modules\cordova-serve\src\browser.js

**Comment by mingdong88** [comment]
> @ mingdong88 could you please check the patch from @krombipils and let us know does it works for you?

Hi,@SounD120 
 It works. Thank you very much.

Best Regards
Ming dong

**Comment by SounD120** [comment]
@mingdong88 , @krombipils looks like this is an external issue for us caused by our dependency from `cordova-serve`. We'll contact it's team and let you know when we will release a new version with this fix.

**Comment by SounD120** [comment]
Hey @mingdong88, @krombipils version 1.6.1 that includes fix for this just have been released, so this issue is not actual anymore.
